### PR TITLE
[Build] Upgrade Gradle to 8.2.1 and AGP to 8.1.0

### PR DESCRIPTION
**Pull request by ParaskP7**
Platform Request: `pdnsEh-13V-p2`
Project Thread: `paaHJt-57Z-p2`

This PR upgraded Gradle to [8.2.1](https://docs.gradle.org/8.2.1/release-notes.html) and AGP to [8.0.2](https://developer.android.com/build/releases/gradle-plugin#agp-8-0-2).

FYI: The [8.1.1](https://docs.gradle.org/8.1.1/release-notes.html) Gradle upgrades had to happen in 2 parts (67e1bd02d91c5b892434b53b7181ea1d57f10af2 and 4f080b069ff6dcb7549ce49ce8c42f808ef57e56). This is because of the breaking changes that this upgrade introduces, including the `AGP` upgrade and its associated breaking changes (namespace, build option, etc).

-----

🚫 Blocked By:

- [ ] `Android Gradle plugin requires Java 17 to run. You are currently using Java 11.`

<details>
    <summary>CI Failure</summary>

```
[2023-07-11T11:31:30Z] FAILURE: Build failed with an exception.
--
  | [2023-07-11T11:31:30Z]
  | [2023-07-11T11:31:30Z] * Where:
  | [2023-07-11T11:31:30Z] Build file '/var/lib/buildkite-agent/builds/ci-android-i-0c37688b1a5352a5d-1/automattic/wordpress-login-flow-android/WordPressLoginFlow/build.gradle' line: 2
  | [2023-07-11T11:31:30Z]
  | [2023-07-11T11:31:30Z] * What went wrong:
  | [2023-07-11T11:31:30Z] An exception occurred applying plugin request [id: 'com.android.library', version: '8.0.2']
  | [2023-07-11T11:31:30Z] > Failed to apply plugin 'com.android.internal.library'.
  | [2023-07-11T11:31:30Z]    > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
  | [2023-07-11T11:31:30Z]       Your current JDK is located in /usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.amzn2.0.1.x86_64
  | [2023-07-11T11:31:30Z]       You can try some of the following options:
  | [2023-07-11T11:31:30Z]        - changing the IDE settings.
  | [2023-07-11T11:31:30Z]        - changing the JAVA_HOME environment variable.
  | [2023-07-11T11:31:30Z]        - changing `org.gradle.java.home` in `gradle.properties`.
```

</details>

-----

Breaking Change List:

1. [Move package from android manifest to build files](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/commit/e1d8d615eafaf66f4117c7772c8aa420a6c5024b)
2. [Enable build config build feature for wordpress login flow](https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/commit/f8ef806249f65c438d75f74f0f199146a5213c6d)

-----

## Associated clients

You can reference the `[Build] Upgrade Gradle to 8.1.1 and AGP to 8.0.2` PRs of the below associated clients for testing/verification purposes:

- [ ] WPAndroid#<PR_NUMBER>
- [ ] WCAndroid#<PR_NUMBER>

-----

## To test

1. Verify that all the CI checks are successful.
4. Test composite builds via the associated clients apps (see above).

-----

## Merge instructions

- [x] Mark PR as `Ready for review`.
- [x] Wait for PR to get approved.
    - [x] TODO: Test all the PRs together once done with the reviews (@oguzkocer).
- [x] Remove `[PR] Not Ready for Merge` label.
- [x] In coordination with all the other library and client PRs, merge this PR only when every PR is ready to be merged.

### CODE REVIEW

**Review by oguzkocer — COMMENTED** [review]
@ParaskP7 I am tentatively approving this PR pending testing. I'll test all the PRs together once I am done with the reviews. Hope that works for you!

**Review by oguzkocer — APPROVED** [review]
Forgot to select `Approve` in my previous review 🤦

**Comment by ParaskP7** [comment]
Awesome @oguzkocer , thanks for adding JDK17 support to this repo, then reviewing and tentatively approving the changes, pending some extra testing! 🙇 ❤️ 🚀 

FYI: I went ahead, marked this PR as `Ready for review` and removed the `[PR] Not Ready for Merge` label. The last thing for us to do is to coordinate the merge wit with all the other library and client PRs, merging this PR only when every other such PR is ready to be merged as well.

**Comment by ParaskP7** [comment]
Thanks for updating the `publish-to-s3` Gradle plugin @oguzkocer , LGTM, you rock! 🙇 ❤️ 🚀

**Pull request merged**
