### PR TITLE
Merge Unified Login & Signup changes from WPAndroid

### PR DESCRIPTION
**Pull request by renanferrari**
This PR merges the changes from the Unified Login & Signup project in WPAndroid.

Here's a list of all included PRs:

- **Functional changes**
  - [Create Sign-Up From Login functionality for Email + Magic Link method](https://github.com/wordpress-mobile/WordPress-Android/pull/11708)
  - [Create Sign-Up From Login functionality for Google Sign-In method](https://github.com/wordpress-mobile/WordPress-Android/pull/11717)
  - [Login with site address from the Prologue screen](https://github.com/wordpress-mobile/WordPress-Android/pull/11780)

- **UI changes**
  - [Prologue screen UI update](https://github.com/wordpress-mobile/WordPress-Android/pull/11876)
  - [Epilogue screen UI update](https://github.com/wordpress-mobile/WordPress-Android/pull/11944)
  - [Login library theme and styles update](https://github.com/wordpress-mobile/WordPress-Android/pull/12047)
  - [Login library screen layouts update](https://github.com/wordpress-mobile/WordPress-Android/pull/12048)
  - [Add Signup Confirmation screen](https://github.com/wordpress-mobile/WordPress-Android/pull/12056)
  - [Disable primary buttons on empty fields](https://github.com/wordpress-mobile/WordPress-Android/pull/12415)
  - [Fix theming-related issues](https://github.com/wordpress-mobile/WordPress-Android/pull/12425)
  - [Fix issues with Gravatar placeholder](https://github.com/wordpress-mobile/WordPress-Android/pull/12428)
  - [Update WordPress-Utils library version](https://github.com/wordpress-mobile/WordPress-Android/pull/12494)
  - [Replace temporary GravatarUtils from the Login library with the updated one from the Utils library](https://github.com/wordpress-mobile/WordPress-Android/pull/12496)

- **Event tracking changes**
  - [Unified login tracking 1   - Screens](https://github.com/wordpress-mobile/WordPress-Android/pull/12089)
  - [Unified login failure tracking](https://github.com/wordpress-mobile/WordPress-Android/pull/12116)
  - [Add click tracking to unified login and signup flow](https://github.com/wordpress-mobile/WordPress-Android/pull/12117)
  - [Add tracking to Signup Confirmation screen](https://github.com/wordpress-mobile/WordPress-Android/pull/12271)
  - [Signup: Add source property to account creation event](https://github.com/wordpress-mobile/WordPress-Android/pull/12503)

The most impactful changes are the ones related to the UI, as both the theme and styles used by the library got a major overhaul. Those changes were reviewed by both WordPress and WooCommerce teams at the time.

Here's a summary of the main breaking changes to watch out for:

- The theme used by the library as well as the styles have all been renamed and updated.
- The structure used by resources (themes, styles, colors) has also been updated.
- A new screen has been added (Signup Confirmation Screen) and `LoginListener` was updated accordingly.
- New tracking events have been added and `LoginAnalyticsListener` was updated accordingly.
- Most screens have new layouts and the base layout used by all of them has also been updated.
- `LoginEmailFragment` is the only screen that has kept both its old and new layouts, which can be switched by using the `shouldUseNewLayout` flag.
- The library now depends on the version 1.26 of the Utils library.

### CODE REVIEW

**Comment by planarvoid** [comment]
> @renanferrari renanferrari requested review from khaykov, planarvoid and AmandaRiu and removed request for khaykov and planarvoid 3 days ago

Github got confused and I'm not sure whether I should review this PR or not :-). It's in the list of my "Review requests" but I'm not listed as a "Reviewer". Is @AmandaRiu enough @renanferrari ?

**Comment by renanferrari** [comment]
Sorry for the confusion, @planarvoid! I had initially requested a review from you and @khaykov but then I talked to the Woo team and decided it was better to leave it to @AmandaRiu, as these changes are most relevant to them.

**Comment by AmandaRiu** [comment]
@renanferrari did an unofficial review of the changes as they pertain to woo-mobile and all looks good. It will be some work for sure, but thanks to you it will be less work 😄. Removing myself as a reviewer since I'm not officially reviewing this PR as discussed in Slack.

**Comment by renanferrari** [comment]
@AmandaRiu Thank you! Your "unofficial review" was actually the only thing pending for this PR, as everything else was already tested in WPAndroid 🙂  Since it also looks good on your side, I'm gonna go ahead and merge it.

**Pull request merged**
