### PR TITLE
Fix tracks connected info property naming

### PR DESCRIPTION
**Pull request by AmandaRiu**
This PR merges the changes defined in this [WCAndroid PR](https://github.com/woocommerce/woocommerce-android/pull/1287). The changes are minor, I just needed to fix the property names of the `_login_connected_site_info_succeeded` event so the properties would get properly saved to the event.

This [Draft PR](https://github.com/wordpress-mobile/WordPress-Android/pull/10321) can be used for testing these changes in WPAndroid.

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @AmandaRiu! The changes look good. My only concerns is if it's a good idea to rename the properties. In general changing names of events or properties isn't a good idea as it will break already existing funnels/queries. This is especially true when the events are related to login/signup/sitecreation as we have some cross-platform funnels which we regularly check. I'm not saying we shouldn't make this change, I just wanted to raise this point. I want to be 100% this change is safe to do. Wdyt?

**Comment by malinajirka** [comment]
ok, just ignore my comment:D. I forgot you actually checked the previous properties were being completely ignored. I'll double check the subtree and merge this PR ;).

**Review by malinajirka — APPROVED** [review]
LGTM 🚢

**Comment by AmandaRiu** [comment]
thanks @malinajirka !! 💃

**Pull request merged**
