### PR TITLE
Encode email delimiter chars defined in RFC 3986

### LINKED ISSUE #15480: Cannot log in using an email address containing a special character such as a single quote
Steps to reproduce:

1. Have an email address that has not been used before to create an account on WordPress.com and that contains a special character such as a single quote.
1. Open the app and log out if you were already logged in.
1. Tap the "Log in or sign up with WordPress.com" button.
1. Enter the email address from step 1.
1. Complete the account creation including any email verification required.
1. Open the app and log out again.
1. Try to log in using the email address from step 1.

**Results:** Signup allows me to use a single quote special character in an email address when I create an account but then I cannot log in when I try to use that email in the login flow. (<a href="https://cloudup.com/caQlMDo8fdx">6m57s</a>) 

**Note:** The error in this case is a bit odd since it mentions a problem with email that I don't think is relevant and shows the signup screen in the background even though an account already exists at that point for the email being tested.

**Error:** 

> There was some trouble sending the email. You can retry now or close and try again later. 

image

<sup>Tested signup using `design5279+android'test101821@gmail.com` using WPAndroid 18.3 Play Store version on Pixel 3 Android 11.</sup>

**App logs:** 

```
33 - [Oct-18 20:36 STATS] 🔵 Tracked: login_email_form_viewed
34 - [Oct-18 20:36 STATS] 🔵 Tracked: unified_login_step, Properties: {"source":"default","flow":"wordpress_com","step":"start"}
35 - [Oct-18 20:36 NUX] LoginEmailFragment: Google API client connected
36 - [Oct-18 20:36 STATS] 🔵 Tracked: unified_login_interaction, Properties: {"source":"default","flow":"wordpress_com","step":"start","click":"select_email_field"}
37 - [Oct-18 20:36 NUX] LoginEmailFragment: Autofill framework is enabled. Disabling hint picker dialog.
38 - [Oct-18 20:37 STATS] 🔵 Tracked: unified_login_interaction, Properties: {"source":"default","flow":"wordpress_com","step":"start","click":"submit"}
39 - [Oct-18 20:37 API] Dispatching action: AccountAction-FETCH_AUTH_OPTIONS
40 - [Oct-18 20:37 API] Volley error on https://public-api.wordpress.com/rest/v1.1/users/design5279+android'test101821@gmail.com/auth-options/?locale=en_GB - exception: null
41 - [Oct-18 20:37 API] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

42 - [Oct-18 20:37 API] Dispatching action: AccountAction-FETCHED_AUTH_OPTIONS
43 - [Oct-18 20:37 API] OnAuthOptionsFetched has error: UNKNOWN_USER - User does not exist.
44 - [Oct-18 20:37 API] Dispatching action: AuthenticationAction-SEND_AUTH_EMAIL
45 - [Oct-18 20:37 STATS] 🔵 Tracked: login_magic_link_open_email_client_viewed
46 - [Oct-18 20:37 STATS] 🔵 Tracked: unified_login_step, Properties: {"source":"default","flow":"signup","step":"magic_link_requested"}
47 - [Oct-18 20:37 API] Volley error on https://public-api.wordpress.com/rest/v1.1/auth/send-signup-email/?locale=en_GB - exception: null
48 - [Oct-18 20:37 API] StackTrace: com.android.volley.ClientError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:199)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:131)
	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

49 - [Oct-18 20:37 API] Dispatching action: AuthenticationAction-SENT_AUTH_EMAIL
50 - [Oct-18 20:37 STATS] 🔵 Tracked: signup_magic_link_failed
51 - [Oct-18 20:37 API] OnAuthEmailSent error: USER_EXISTS - User with this email already has an account.
52 - [Oct-18 20:37 STATS] 🔵 Tracked: unified_login_failure, Properties: {"source":"default","flow":"signup","step":"magic_link_requested","failure":"There was some trouble sending the email. You can retry now or close and try again later."}
53 - [Oct-18 20:37 UTILS] App goes to background
54 - [Oct-18 20:37 STATS] 🔵 Tracked: application_closed, Properties: {"time_in_main_reader":2,"last_visible_screen":"Unknown","time_in_reader_paged_post":0,"time_in_app":113,"time_in_subfiltered_list":0,"time_in_reader_filtered_list":0}
```

**Workaround:** Log in to the affected WordPress.com account using a web browser, go to WP Admin > Profile > Get Apps and use the "Email me a log in link" to get a magic login link.

**Notes:** On the web, it's possible to log in by username instead of email address as an easy workaround. In the iOS app, login is completely blocked by this. In the Android app, there's actually a workaround which is to use the magic login link from the Get Apps page on the web so while it's still a problem for affected users it's not as urgent as it is for the iOS app.

<sup>(internal reference: p4a5px-2MC-p2 /hat tip @mdrockwell)</sup>

### PR DESCRIPTION
**Pull request by jd-alexander**
Fixes https://github.com/wordpress-mobile/WordPress-Android/issues/15480

Related PRs:
- https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2171
- https://github.com/wordpress-mobile/WordPress-Android/pull/15526

## Description 

Encodes delimiters in email addresses when calling the `auth-options` endpoint, based on the [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) specification.

See: [Similar fix in iOS](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/457).

More info in this issue comment: https://github.com/wordpress-mobile/WordPress-Android/issues/15480#issuecomment-1202342661.

🚀 It also updates the Kotlin Version to `1.6.10` to restore Buildkite CI checks success when building this Repo.

**To Test:**
Follow the testing steps from the integrating PR: https://github.com/wordpress-mobile/WordPress-Android/pull/15526.

## Merging Strategy

**Notice** ✅ One review should be enough to merge these PRs.
Check the [merging strategy](https://github.com/wordpress-mobile/WordPress-Android/pull/15526) in the `WordPress-Android` PR.

### CODE REVIEW

**Comment by ovitrif** [comment]
@ParaskP7 I'm requesting your review since this is also bumping the Kotlin version, as we've agreed early today (ref: p1659510263238549/1659449153.829029-slack-C02QANACA) 👋 🙇 .

I didn't run into issues when manually testing the login & signup flow, though your feedback on what to check is needed before proceeding with this 💯 .

**Comment by ParaskP7** [comment]
👋 @ovitrif !

Thank you for the ping and for adding me as a reviewer here! 🙏 

> @ParaskP7 I'm requesting your review since this is also bumping the Kotlin version, as we've agreed early today (ref: p1659510263238549/1659449153.829029-slack-C02QANACA) 👋

Ah, I thought this would be a separate PR, where we will just update the Kotlin version, smoke test that change in isolation to any other change, then after merging this change first, you would update the PR and use this new Kotlin version here.

But, if that all sounds too complicated, we can do it this way too, especially if you are in a hurry... 😅 

PS: Is it okay if I do the review tomorrow?

**Comment by ovitrif** [comment]
> PS: Is it okay if I do the review tomorrow?

That's perfectly fine for me @ParaskP7, no rush 👍 .

> Ah, I thought this would be a separate PR, where we will just update the Kotlin version, smoke test that change in isolation to any other change, then after merging this change first, you would update the PR and use this new Kotlin version here.

That's probably a better idea, the reason I started with this approach is because I wasn't 💯 sure the problem was caused by the older Kotlin version, and this came as I was investigating why both the CI environment and myself couldn't build this branch 😄 .

I could prepare a PR only for the Kotlin version bump, although the changes in this PR helped find out the issue, and apparently the problem appears when we're referencing a dependency compiled with a Kotlin version newer than what's currently on `trunk` for this repo.

What do you suggest? I'm fine with both.

If I don't have to prepare another PR I promise to spend the saved time wisely, investigating another user-facing Groundskeeping issue 😅 (the stakes have been raised 👀).

**Comment by ParaskP7** [comment]
👋 @ovitrif !

> That's perfectly fine for me @ParaskP7, no rush 👍 .

Coolio 👍 !

> That's probably a better idea, the reason I started with this approach is because I wasn't 💯 sure the problem was caused by the older Kotlin version, and this came as I was investigating why both the CI environment and myself couldn't build this branch 😄 .

😄 

> I could prepare a PR only for the Kotlin version bump, although the changes in this PR helped find out the issue, and apparently the problem appears when we're referencing a dependency using a Kotlin version newer than what's currently on trunk for this repo.

👍 

> What do you suggest? I'm fine with both.
> 
> If I don't have to prepare another PR I promise to spend the saved time wisely, investigating another Groundskeeping issue 😅.

😅 Let's keep it simple then this time, but let's be aware that for next time it might be beneficial if we have separate PRs and testing for such changes, especially when that involves `Gradle`, `AGP`, `Kotlin`, `Dagger` or other such major libraries.

In this case, the version bump is also significant, from `1.4.32` to `1.6.10`, 2 major versions up, thus this might also require a bit more focused review and testing. As long as you are comfortable with this change, and the testing you did shows that everything is okay, I am okay to review it too.

PS: If I could chose, I would change your promise to instead spend the saved time testing this Kotlin change instead of another Groundskeeping issue... 😛

**Comment by ovitrif** [comment]
> PS: If I could chose, I would change your promise to instead spend the saved time testing this Kotlin change instead of another Groundskeeping issue... 😛

Sounds fair to me ! 🧘🏻 🚦

**Review by ParaskP7 — COMMENTED** [review]
👋 @ovitrif !

I have reviewed this PR, mainly focusing on the Kotlin change and any side effects (didn't find any), everything LGTM and thank you for making the upgrade and also for adding the extra `OVERRIDE_DEPRECATION` suppression to get rid of this new warning. 💯 

It it a 👍 from my side on the Kotlin change. I also tested it with composite builds to verify that nothing weird is happening on that side too, that is, when enabling both `localFluxCPath` and `localLoginFlowPath` as local builds. ✅

FYI: I am going to let the testing and merging part for someone else (more fit for it, thinking @mkevins) since this change involves multiple PRs, and I am seeing Matthew has already reviewed most of them.

**Comment by ovitrif** [comment]
> 👋 @ovitrif !
> 
> I have reviewed this PR, mainly focusing on the Kotlin change and any side effects (didn't find any), everything LGTM and thank you for making the upgrade and also for adding the extra `OVERRIDE_DEPRECATION` suppression to get rid of this new warning. 💯
> 
> It it a 👍 from my side on the Kotlin change. I also tested it with composite builds to verify that nothing weird is happening on that side too, that is, when enabling both `localFluxCPath` and `localLoginFlowPath` as local builds. ✅
> 
> FYI: I am going to let the testing and merging part for someone else (more fit for it, thinking @mkevins) since this change involves multiple PRs, and I am seeing Matthew has already reviewed most of them.

Many thanks for reviewing & testing thoroughly the Kotlin version upgrade @ParaskP7 🙇 , you are awesome 🥇 💯 🚀 

I'm glad everything went ok also in your testing 👍 

I'm afraid @mkevins might have forgotten to approve this one when testing the whole changeset integrated in the WordPress-Android PR https://github.com/wordpress-mobile/WordPress-Android/pull/15526, we'll probably will only be able to merge this on Monday since his weekend started a bit earlier this week ✈️ 🌎 🇺🇸, 😃.

**Review by mkevins — APPROVED** [review]
> I'm afraid @mkevins might have forgotten to approve this one when testing the whole changeset integrated in the WordPress-Android PR https://github.com/wordpress-mobile/WordPress-Android/pull/15526, we'll probably will only be able to merge this on Monday since his weekend started a bit earlier this week

Indeed, I hadn't realized the WordPress-Login-Flow was also part of this since the ref update was not in the changeset at the time I reviewed it 😅 .

I have retested this (via the main WordPress-Android app PR) and this is working as expected. Also, these code changes look good. Nice work Ovi!

**Comment by ovitrif** [comment]
> Indeed, I hadn't realized the WordPress-Login-Flow was also part of this since the ref update was not in the changeset at the time I reviewed it 😅 .

True, I made a mistake there not updating the integrating PR to reference to the Login-Flow version of this PR 🥲.

> I have retested this (via the main WordPress-Android app PR) and this is working as expected. Also, these code changes look good. Nice work Ovi!

Thanks a lot for testing again the changes 🙇 , I've merged with `trunk` and updated the FluxC-Android version to the new one that includes the PR we've merged to FluxC last week 🎉 

One last version juggling and then I can merge this & the WordPress Android PR 🚀 :shipit:

**Pull request merged**
