### PR TITLE
Google login fix

### PR DESCRIPTION
**Pull request by planarvoid**
This merges the changes already in WPAndroid into the login library - https://github.com/wordpress-mobile/WordPress-Android/pull/10523

Do the other commits feel right? The only change I haven't done is the Jitpack update

### CODE REVIEW

**Comment by malinajirka** [comment]
Thanks @planarvoid! I haven't tested the functionality as I assume it was tested in the WPAndroid PR. I've only checked that the correct version of git was used.

One question though: Do you think this change might also fix - https://github.com/wordpress-mobile/WordPress-Login-Flow-Android/issues/7 ?

**Review by malinajirka — APPROVED** [review]

**Comment by malinajirka** [comment]
cc @AmandaRiu @0nko You might want to consider merging this fix into Woo.

**Comment by AmandaRiu** [comment]
Thanks @malinajirka, will do.

**Comment by planarvoid** [comment]
@malinajirka I think it might fix both (or neither if the issue was somewhere else :-) )

**Pull request merged**
